### ISSUE TITLE
Publish state?

### ISSUE THREAD

**Issue by imurchie** [jlipps/mapify#4]
The state of this package is _odd_...
```
$ npm view es6-mapify dist-tags
{ latest: '1.0.2' }

$ npm view es6-mapify versions
[ '1.0.0', '1.0.1', '1.0.2', '1.1.0' ]
```

So, version `1.1.0` is the "latest", though not tagged as such on npm. But it is not in github, and has earlier dependencies than `1.0.2`, most notably it is still pinned to `babel-runtime@5.8.24`.

I think the best thing to do would be to fully publish a new new minor version, with all the updates to dependencies.

**Comment by jlipps** [comment]
Yes, that was weird. Not sure what happened. 1.2.0 has been published.

**Comment by imurchie** [comment]
Excellent! Thanks!
